### PR TITLE
Anon1234 changes

### PR DESCRIPTION
**Pull request by mdirkse**
From https://github.com/proxypoke/i3ipc/pull/7

### CODE REVIEW

**Comment by mdirkse** [comment]
@tep could you check that this meets your needs?

**Comment by brunnre8** [comment]
Can you please merge those changes?

**Comment by tep** [comment]
MY apologies -- somehow this slipped through the cracks.  These changes are just what I was looking for.
Thank you.

**Comment by mdirkse** [comment]
Will try to merge these changes as soon as possible

**Pull request merged**
